import { convexAuth } from '@convex-dev/auth/server';
import { Password } from '@convex-dev/auth/providers/Password';

/**
 * Convex Auth configuration.
 *
 * Providers:
 *   - Password — email + password (sign-up and sign-in)
 *
 * To add OAuth providers (GitHub, Google, etc.) in the future:
 *   import GitHub from '@auth/core/providers/github';
 *   providers: [Password, GitHub]
 *
 * Environment variables required (set in Convex dashboard):
 *   JWT_PRIVATE_KEY   — generated by `npx @convex-dev/auth`
 *   JWKS              — generated by `npx @convex-dev/auth`
 *   SITE_URL          — your app's URL (used for OAuth callbacks)
 */
export const { auth, signIn, signOut, store, isAuthenticated } = convexAuth({
  providers: [Password],
});
